[package]
name = "kugelfisch"
version = "0.1.0"
authors = ["Carbon <carbon.szlachta@gmail.com>"]
edition = "2018"
repository = "https://github.com/Carbon225/kugelfisch"

[dependencies]
rand = "0.8.3"
blake2 = "0.9.1"

[dev-dependencies]
predicates = "1"
assert_cmd = "1"
tempfile = "3"
