name: Build master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-2019', 'ubuntu-20.04']
        
    runs-on: ${{ matrix.os }}
            
    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Upload artifacts
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v2
      with:
        name: kugelfisch-debug-windows-amd64
        path: target/debug/kugelfisch.exe
    
    - name: Upload artifacts
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/upload-artifact@v2
      with:
        name: kugelfisch-debug-linux-amd64
        path: target/debug/kugelfisch
